### ISSUE TITLE
Add Earnnest as a GET sponsor to East

### ISSUE THREAD

**Issue by BigBlueHat** [RESTFest/2019.restfest.org#15]
Sponsors woot! 😸

Website: https://www.earnnest.com/

Below is an SVG (in a zip file...because GitHub is weirdly more scared of than zip...) of their logotype.
[logo__earnnest-wordmark.zip](https://github.com/RESTFest/2019.restfest.org/files/3517257/logo__earnnest-wordmark.zip)

**Comment by oestrich** [comment]
On the site!
