### ISSUE TITLE
Banner image for EU event

### ISSUE THREAD

**Issue by BigBlueHat** [RESTFest/2019.restfest.org#2]
http://2019.restfest.org/eu/ needs a pretty image of Wroclaw. 😃 

See http://2019.restfest.org/midwest/ for an example.

We generally put photo credits in the bottom right corner of the site.

**Comment by tpluscode** [comment]
You got you from Flickr. Here's some for [Wrocław](https://www.flickr.com/search/?text=wrocław&license=2%2C3%2C4%2C5%2C6%2C9) I think may work. Search filtered for CC only

## Market square

Wrocław's classic. Colorful buildings, and wide crop easily possible.

This one's nice; vivid and wide:

[![](https://farm7.staticflickr.com/6199/6085714345_b1bd4e470a_z.jpg)](https://www.flickr.com/photos/paracon/6085714345/in/photolist-agLSRp-6RxXPY-sbXLVa-agPETA-YWAtmo-5zAbuB-4JpZHu-nXx6wC-54DN7v-4iGVjQ-4iCSHM-4iCVkg-4iCMGP-jNN6Y6-4iCTnB-4iCSnt-4iGTsS-ecy38J-q2pJXP-EPfZ9c-24qFJnC-GyWub7-QHtStQ-9rywTL-UQMEPp-4iCWYV-7rubpq-24poJQS-TDCEGu-SDLnwa-EP1o38-21JGNiW-26Vyqn2-9sZYRx-aq9iYk-aqcjQo-ecxJv5-aq9rW6-24pkS4f-TL2JiN-HtY1Gg-5zEtFJ-4Jq1eJ-CaC8nQ-9PG878-gXaRYH-6V2KU5-jyiKQS-nDpGyk-4JjLck)

Next two aren't nicely framed but weirdly tinted (same author)

[![](https://farm9.staticflickr.com/8069/8200084899_c736916132_c.jpg)
](https://www.flickr.com/photos/giewor/8200084899/in/photolist-duBzy8-aqcAej-aq9Njn-24uzcgM-6xg9oh-54JfSS-5PPot4-Geisci-aq9dKK-TDCD8s-EQ6sAR-duByBB-29ucxYn-aqc9p5-Gk9yDT-gMNjt-8qxopT-8qApVL-8qxeDp-28oW2bb-woR7H-aqc9T3-GkH27G-woR7K-84JSiA-9RTDpy-4Jq9Tf-9RQLAi-iJfNdw-2ba5y6H-8yYuCz-N6xmuZ-MgsrnW-Mgsqjy-8W8fTR-9KTFJ4-9RTCt9-adiCXZ-9RQGuR-AkoSCz-4sQnUE-5GQxmS-A2Q6DQ-A2VaPz-7oNLrj-4JoN8b-4JjHbR-AjpUXH-iJd9NT-9PG7pn)

[![](https://farm9.staticflickr.com/8202/8200081737_7fbf9f3c95_c.jpg)
](https://www.flickr.com/photos/giewor/8200081737/in/photolist-duByBB-29ucxYn-aqc9p5-Gk9yDT-gMNjt-8qxopT-8qApVL-8qxeDp-28oW2bb-woR7H-aqc9T3-GkH27G-woR7K-84JSiA-9RTDpy-4Jq9Tf-9RQLAi-iJfNdw-2ba5y6H-8yYuCz-N6xmuZ-MgsrnW-Mgsqjy-8W8fTR-9KTFJ4-9RTCt9-adiCXZ-9RQGuR-AkoSCz-4sQnUE-5GQxmS-A2Q6DQ-A2VaPz-7oNLrj-4JoN8b-4JjHbR-AjpUXH-iJd9NT-9PG7pn-9RQKVV-5hZ55c-4Sg2oa-5i4rVC-4JkWF4-5i4r1h-5hZ8eH-5jvfSJ-6xgDSh-237TbHF-nBtqr)

## Salt market

A smaller square, adjacent to main market square. The 24/7 flower shops stand out

[![wro](https://farm9.staticflickr.com/8252/8662354237_22d3317076_c.jpg)
](https://www.flickr.com/photos/alexander_johmann/8662354237/in/photolist-ecsQ88-aqc1DU-aqciku-GDT2Jt-aq9EXP-5PTS2C-24uuYyk-aqcnV1-aqciMN-aq9R2X-aqccEs-aqcFGA-24rgzmo-aqcors-aq9T36-nCvVRz-aqcDH3-aq9Jjz-aqbYdL-5c1gFn-aq9ekz-6HSqHR-7tsrEL-aqcCKJ-aqcB25-aq9kR2-aqcvvA-aqcA1h-aq9uDV-aqcgM9-5PUL3W-eb5aWG-aq9xae-GkCGz9-aq9C4T-aq9D7R-aq9S6X-apu7Qs-aqcEJw-EP2DpD-Tyn7R7-aqchey-aq9KnM-fkwGfb-aq9Zb6-aq9Mtc-aqcoYL-8tv3Dq-5PUPVw-EPbrC4)

## River and uni from above

Odra river is big deal in Wrocław.

[![](https://farm3.staticflickr.com/2862/33245206073_2009ff66f4_c.jpg)
](https://www.flickr.com/photos/91875255@N05/33245206073/in/photolist-SDLnwa-EP1o38-21JGNiW-26Vyqn2-9sZYRx-aq9iYk-aqcjQo-ecxJv5-aq9rW6-24pkS4f-TL2JiN-HtY1Gg-5zEtFJ-4Jq1eJ-CaC8nQ-9PG878-gXaRYH-6V2KU5-jyiKQS-nDpGyk-4JjLck-aS4Huv-W5e88P-nynqZr-n4ebog-2eLp9-4tCd7T-4JkQt6-4Jq2v1-Zwuycq-ecsqWc-23ouUNG-54HRLq-aqcrTo-rY6TUU-aq9B3B-TPUQ4Y-aqccb9-aqcqWw-UoEYN9-aqcdJL-aQL6Pg-aqcfcE-ecsQ88-aqc1DU-aqciku-GDT2Jt-aq9EXP-5PTS2C-24uuYyk)

The next one similar, but slightly narrow angle to crop

[![](https://farm8.staticflickr.com/7272/7151648837_4005e0a424_c.jpg)
](https://www.flickr.com/photos/polandmfa/7151648837/in/photolist-bTY53i-aq9Ybk-aqcAvY-aqbVJb-U2qxAj-kMseyo-GbZFFb-eaYzGF-eaYCg2-FpGEdC-FpSR8n-FpSKRF-aq9miZ-aq9fZ4-aqc6MY-FV39GL-ecstAV-duBDi2-aqc5ZQ-238jSuz-ER4ygB-FpGk21-GhRz7o-5NXfPW-aq9qqR-54E4Qt-GDT2za-aoHTus-24uhvAr-6xgBtN-aqcJHh-GbZfoN-NHnLzd-5PQvED-FpSUYt-bTY5mz-duByX6-Gk9Ah2-bW7gtP-ER6fdt-GmyPkA-FpGsgw-duBzy8-aqcAej-aq9Njn-24uzcgM-6xg9oh-54JfSS-5PPot4-Geisci)

## More river

I mention the river, so here are some which [reveal less architecture](https://www.flickr.com/search/?license=2%2C3%2C4%2C5%2C6%2C9&text=wrocław%20odra&advanced=1)

[![](https://farm5.staticflickr.com/4619/39975685552_eb507f8878_c.jpg)
](https://www.flickr.com/photos/128730796@N02/39975685552/in/photolist-23UvQzN-23zTkSE-24MMYSw-23yKwRJ-24JAsxw-54Jjiy-25mJYdG-24sGWmn-243v8tU-21UEXbj-dXZ1xb-fJfExs-bTY53i-KRgZJ-fLcsHC-24SeQ1W-5PPot4-WQi1P6-hGSVxB-YtCgPJ-9RTC69-WeVxFu-54JiWo-26RCzoL-nN4bxT-dFm3Xc-HvDKQy-dgBAgE-fFNfcU-fTUtkn-7fNBdd-fKzQUw-dgBDLd-6w6vSS-9UhkBB-fJfwSN-K51jq4-VCzMkB-fFvCJF-WNyRhS-8dFYwb-WSdF9R-JoH42Y-WB8XTj-4rwu6H-4rwuMK-8FUTMD-4rAwcJ-coKgfm-WABV2X)

[![](https://farm5.staticflickr.com/4322/36010420876_4cc2e56741_c.jpg)
](https://www.flickr.com/photos/petrolly/36010420876/in/photolist-WS7Pxs-23UvQzN-23zTkSE-24MMYSw-23yKwRJ-24JAsxw-54Jjiy-25mJYdG-24sGWmn-243v8tU-21UEXbj-dXZ1xb-fJfExs-bTY53i-KRgZJ-fLcsHC-24SeQ1W-5PPot4-WQi1P6-hGSVxB-YtCgPJ-9RTC69-WeVxFu-54JiWo-26RCzoL-nN4bxT-dFm3Xc-HvDKQy-dgBAgE-fFNfcU-fTUtkn-7fNBdd-fKzQUw-dgBDLd-6w6vSS-9UhkBB-fJfwSN-K51jq4-VCzMkB-fFvCJF-WNyRhS-8dFYwb-WSdF9R-JoH42Y-WB8XTj-4rwu6H-4rwuMK-8FUTMD-4rAwcJ-coKgfm)

Night shot?

[![](https://farm5.staticflickr.com/4745/38851321325_be83d3dba7_c.jpg)
](https://www.flickr.com/photos/128730796@N02/38851321325/in/photolist-22cabgF-bTY5mz-JoDuYD-267ytT6-nynqZr-5PTS2C-74HXoc-2b85uxD-WS7Pxs-23UvQzN-23zTkSE-24MMYSw-23yKwRJ-24JAsxw-54Jjiy-25mJYdG-24sGWmn-243v8tU-21UEXbj-dXZ1xb-fJfExs-bTY53i-KRgZJ-fLcsHC-24SeQ1W-5PPot4-WQi1P6-hGSVxB-YtCgPJ-9RTC69-WeVxFu-54JiWo-26RCzoL-nN4bxT-dFm3Xc-HvDKQy-dgBAgE-fFNfcU-fTUtkn-7fNBdd-fKzQUw-dgBDLd-6w6vSS-9UhkBB-fJfwSN-K51jq4-VCzMkB-fFvCJF-WNyRhS-8dFYwb)

**Comment by BigBlueHat** [comment]
Of these I like 1, 3, 7, and 9...but probably in this order: 1, 9, 7, 3. 😁 

@tpluscode feel free to pick one, crop it to the size currently in place, and add it to the repo. You should have commit bit here.

**Comment by tpluscode** [comment]
This is plain github pages?

**Comment by BigBlueHat** [comment]
> This is plain github pages?

Yep! The EU site is available at http://2019.restfest.org/eu/

The http://2019.restfest.org/ URL redirects to http://restfest.org/

Once we're done setting up the sub-sites, we'll link off restfest.org and announce these.

**Comment by tpluscode** [comment]
Got some of those roughly positioned to see how they perform

[Option 1](https://deploy-preview-1--optimistic-benz-f99123.netlify.com/eu/) - Too colorful IMO. Looks nice on its own but I think it's too distracting to be a background. Besides it had to be enlarged...

[Option 9](https://deploy-preview-2--optimistic-benz-f99123.netlify.com/eu/) - Not bad, I guess.

[Option 7](https://deploy-preview-3--optimistic-benz-f99123.netlify.com/eu/) - I like how the text lands on the sky and roofs. I don't like the towers cut off :)

[Option 3](https://deploy-preview-4--optimistic-benz-f99123.netlify.com/eu/) - to my surprise, this may be my favourite. The tint makes it a bit more neutral and work better with text on top.

[Option 4](https://deploy-preview-5--optimistic-benz-f99123.netlify.com/eu/) - additional choice. the narrow angle makes me feel... intimate with the architecture. I think it works quite well given how unappealing the image seems on its own

@BigBlueHat @switzersc @rmaziarka @pawelklimczyk opinons?

**Comment by BigBlueHat** [comment]
Great demo and thoughts! I like 3 or 4 personally--with a slight preference toward 4 for the reasons you mentioned. 😃
